# Starship Prompt Configuration

[gcloud]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[openstack]
disabled = true

[package]
disabled = true

[git_status]
ahead = "[⇡${count}](purple)"
behind = "[⇣${count}](purple)"
diverged = "[⇡${ahead_count}⇣${behind_count}](purple)"
conflicted = "[=$count](red)"
modified = "[!$count](yellow)"
staged = "[+$count](green)"
untracked = "[?$count](blue)"
format = '($ahead_behind )($conflicted )($modified )($staged )($untracked )'
